### ISSUE TITLE
[FEATURE REQUEST] - Online Editor

### ISSUE THREAD

**Issue by RedSparr0w** [Adrianotiger/desktopPet#11]
A couple of features i think would be pretty useful for the online editor.

- [x] Ability to Delete Pets.
- [x] Ability to Delete Spawns, Animations, Children.
- [x] Auto add `ID` to Spawns, Animations when you create a new one (Still allow it to be editable).
- [x] Auto fill `Repeats Count` and `Repeats From` fields as `0` when you create a new animation.
    - ![image](https://cloud.githubusercontent.com/assets/7288322/23678636/cf710700-03e9-11e7-97c6-c067179e9cc7.png)

- [x] Change `Next Probability` to select element
    - ![image](https://cloud.githubusercontent.com/assets/7288322/23678527/5bcca1ba-03e9-11e7-97e4-855b6d2e72e3.png)
- [x] Change Child `Animation Id` and `Next` to select elements
- [x] Add ability to import xml file
- [x] On the image grid window, resize the image to `height: 100vh; width: 100vw;` once the page has finished loading (only needed if image to large but shouldn't affect other images anyway)
  - Before: ![image](https://cloud.githubusercontent.com/assets/7288322/23678742/43bca6fa-03ea-11e7-9ac9-2915c9632cf9.png)
  - After: ![image](https://cloud.githubusercontent.com/assets/7288322/23678786/626957f6-03ea-11e7-9605-6ea8cb3c4496.png)

**Comment by Adrianotiger** [comment]
Hey, a lot of work for a simple online editor! ;) To be honest, I already know that the editor isn't really good and after I saw what it should be do, I was thinking to create an offline editor (would be even better) or implement the editor inside the main application. It was easy as it was a simple xml. Now that you can do a lot of things and it is more complex, the script is always more complicated to update and so the webpage.

But I will add some functionality in the next days, when I have some time ok? :)

**Comment by Adrianotiger** [comment]
I updated the script a little bit. The select element slows really much the webpage! It need up to 1 minute to load all animations on the eSheep animation :P

Need to find a better solution.

**Comment by RedSparr0w** [comment]
Nice!
Working well, the first time I loaded it I got stuck in some sort of loop as it loaded up to >150% before chrome crashed XD.

Not sure what happened seems like a 1 time thing though.

Yeah an offline editor built into the program would probably be a lot faster and easier, although it may be worth keeping it as a separate thing as most people wouldn't use it (due to just wanting the pet) so no need to include it by default.

You may be able to make it using node.js and electron, as that would most likely make it a lot faster and you could reuse a lot of the current code you have.

If you do decide to go the node.js route let me know and I may be able to help out with it [=

Sent from my iPhone

On 9/03/2017, at 6:23 AM, Adriano <notifications@github.com<mailto:notifications@github.com>> wrote:


I updated the script a little bit. The select element slows really much the webpage! It need up to 1 minute to load all animations on the eSheep animation :P

Need to find a better solution.

**Comment by Adrianotiger** [comment]
Probably you need to reload/refresh the scripts if you got 150%.
100 animations means (6 + 5 + 5) * 100 select boxes with each 100 entries. This mean 160'000 option items to add. It's funny because this doesn't need much to be created. What need much time is to set the right selected item on each select box. A better way would be use a simple textbox (like before) and draw a select box once the user clicks on the textbox. But is not so nice to see and not so comfortable like now.
Anyway, on Chrome/Opera/Vivaldi it take 5-10 seconds to load 100 animations now. On Edge it still take 30 seconds 😢 

But now, you can export the XML, you can import to replace your pet  and even remove your pet from server!

**Comment by RedSparr0w** [comment]
**Nice work!**

The editor is working really well now and loading very fast!
Don't think there is any other things which need doing there, thanks for all your work on this project.
:smile:
