### ISSUE TITLE
eSheep not making any sound

### ISSUE THREAD

**Issue by Ferkner** [Adrianotiger/desktopPet#125]
I have the eSheep setting for sound checked so it should be making the odd noise, but it is always silent. Are sounds included with this version?

**Comment by Adrianotiger** [comment]
The original one does not play any sound. If you open the option page from the app, you can download another sheep with more animations and sounds (wrote from another user)

**Comment by Ferkner** [comment]
Perfect, thank you! These are the sounds I miss!
