### ISSUE TITLE
[FEATURE REQUEST] Multi Monitor Support

### ISSUE THREAD

**Issue by RedSparr0w** [Adrianotiger/desktopPet#13]
If possible multi monitor support would be an awesome addition.
:smile:

**Comment by Adrianotiger** [comment]
Yes, this is of course a good implementation for the future. But I will implement it only once the pet works like expected and has the same functionality like the old eSheep (example detection between multiple pets). I have 2 monitors too, with different resolutions. So this could be a little bit more difficult to implement...

**Comment by RedSparr0w** [comment]
Fair enough, i could imagine it would take quite a bit of work, especially dealing with monitors of different resolutions and placement.

Could possibly add an option to select 1 specific monitor?

**Comment by Adrianotiger** [comment]
Will be available in one of the next releases, in the new UWP-App.
