### ISSUE TITLE
[BUG] Editor - (Flip) showing in wrong section

### ISSUE THREAD

**Issue by RedSparr0w** [Adrianotiger/desktopPet#14]
For some reason the 'repeats from' field is showing as the 'action' (it still applies it as the action in the application though)
_repeats from: flip_
![image](https://cloud.githubusercontent.com/assets/7288322/23977691/7926654a-0a54-11e7-9e84-d0ce9899c05e.png)
The 'action' options are still `-` and `flip` though.

**Comment by Adrianotiger** [comment]
Hi RedSparrow!
Thank you really much for discovering this bug. And sorry for it! My copy/paste was too fast when I tried to make this script faster.
Hope this bug didn't bricked your xml!
It is now solved.

**Comment by RedSparr0w** [comment]
Seemed to update fine, sometimes it would come up saying invalid xml, but most of the time it was fine.

Thanks for fixing it :smile:
