### ISSUE TITLE
[UI] Display value on sliders

### ISSUE THREAD

**Issue by RedSparr0w** [Adrianotiger/desktopPet#16]
Thanks for the latest update!
But one good thing that would be useful is to see the actual value of the sliders.
![image](https://user-images.githubusercontent.com/7288322/29258729-2bdf4b84-8110-11e7-890c-1f1bc7616e32.png)
![image](https://user-images.githubusercontent.com/7288322/29258753-450c1d3a-8110-11e7-877e-9606205f6cad.png)

sidenote: may be useful to just merge those 2 tabs as i would consider those both "options"?

**Comment by RedSparr0w** [comment]
maybe like this:
![image](https://user-images.githubusercontent.com/7288322/29258944-574e2478-8112-11e7-9f41-eb48249ff8a8.png)
or this:
![meh](https://user-images.githubusercontent.com/7288322/29259006-be93db96-8112-11e7-922d-9738c0302510.png)
I don't really know though, just some ideas 😄

**Comment by Adrianotiger** [comment]
You're right. The Option form is miserable, hehehe
At beginning I was thinking to add hundreds of options... Now I still have 2-3 settings. I will redesign this form I think with a better UI. Give me some days ;)

**Comment by Adrianotiger** [comment]
The entire Option window and slidebars are now in UWP-style and for Windows 10.
