### ISSUE TITLE
Sheep falls through window

### ISSUE THREAD

**Issue by koenderks** [Adrianotiger/desktopPet#20]
My sheep falls through my window.

**Comment by Audreth** [comment]
try putting the windows near the bottom right of the screen.

**Comment by Adrianotiger** [comment]
It happens with new versions of Windows 10 (since 5-6 months). Need to check why the window collision does not work anymore like expected. Funny: on top most windows it works...

**Comment by Adrianotiger** [comment]
Will be solved in the next release (UWP-App). Windows detection will be faster and more reliable.
