### ISSUE TITLE
1.0.7 Source

### ISSUE THREAD

**Issue by Deltafox79** [Adrianotiger/desktopPet#24]
Hi I have see v1.0.7 exe is avaiable to download but github is stop to v1.0.6 any upgrade source is scheduled? Regards

**Comment by Adrianotiger** [comment]
Probably the release was never created. I am working on a new release (1.9). Give me just some days to add the multi-screen features and the code will be merged in the main branch.

**Comment by Deltafox79** [comment]
Ok Thank's you for the reply.  Have a nice day

**Comment by Adrianotiger** [comment]
Version 2.0 is now available in the store and in the release.
