### ISSUE TITLE
Use https on website

### ISSUE THREAD

**Issue by RedSparr0w** [Adrianotiger/desktopPet#25]
https://esheep.petrucci.ch/

Using [Lets Encrypt](https://letsencrypt.org/)/[SSL For Free](https://www.sslforfree.com/) are quick, easy and free options.

**Comment by Adrianotiger** [comment]
Yes, I know. I already have another server with a valid SSL, but I still have the webpage on my old server. I need to move it, but never find the motivation to do it...
Is there something that need the https?

**Comment by RedSparr0w** [comment]
Nothing *needs* it per say, But I made a simple chrome extension which uses your `.js` file from the main website to load the pets on any page.
https://github.com/RedSparr0w/DesktopPet_ChromeExtension

But it only work on `https` websites if the source is also `https`, So I currently just load the data from my website: https://esheep.redsparr0w.com/5 which grabs it from yours :laughing:

**Comment by Adrianotiger** [comment]
Use the github xml, it load faster and is https:)

**Comment by RedSparr0w** [comment]
:+1: That works for the default Sheep pet, but not if you want to load any others.

**Comment by Adrianotiger** [comment]
Done 💯%

I moved the entire page, the entire DB to the new server and updated the code to PHP7 😄 

I don't know if https was the only reason. Some times, the server must provide also a "Access-Control-Allow-Origin:*" in the header.

But everything should work now and page is redirected automatically to https.
