### ISSUE TITLE
0% Volume isn't zero volume

### ISSUE THREAD

**Issue by peturdainn** [Adrianotiger/desktopPet#37]
When selecting 0% as volume I can still hear it in my headphones. Not loud but is there.
(as discovered with the green eSheep)

Maybe disable sound entirely if set to 0% ?

Thanks!

**Comment by peturdainn** [comment]
If I go back to options it is still set to 0%. Any place where I can check this? Is it stored somewhere accessible?

**Comment by Adrianotiger** [comment]
I found the problem: if you change volume, it will be updated only on the next start. If you close the app, it works... Until you change the volume again.

Thank you for your feedback!

**Comment by peturdainn** [comment]
Great find and thanks again for giving us this blast from the past (even if I can only use it at work, no Windows systems at home)

**Comment by Adrianotiger** [comment]
Should be solved with the last release.
Thank you again for reporting it and for your donation :)

**Comment by peturdainn** [comment]
thanks for fixing & you're welcome!
