### ISSUE TITLE
MacOS port?

### ISSUE THREAD

**Issue by 0xnurl** [Adrianotiger/desktopPet#38]
Thank you so much for this lovely app. 
Any thoughts on porting it to MacOS? What would it take in order to do that?

**Comment by Adrianotiger** [comment]
I am sorry, but this is impossible with the current code.

It is written in .NET (a Windows programming language) and use user32.dll (Windows system components) to detect and get a list of windows on the screen.

Under linux, there are other components (not sure) to detect windows on the screen. And probably you have to execute the application with root privileges to be able to detect other windows.

It would be easier to write it from 0, than port this code, I think. Sorry.
