### ISSUE TITLE
Noticed in new commits used Tabs not spaces ?

### ISSUE THREAD

**Issue by rluiten** [Adrianotiger/desktopPet#4]
The rest of your code base which i snooped around last night was space indented new commits are Tabs.
I tend to prefer spaces,but that's not the point, pick one or other and and stick to it :)

Cheers!

**Comment by Adrianotiger** [comment]
I work always with tabs (if you don't like the 4-space indeed you can change it). I had a buggy visual studio addon that added spaces and replaced the tabs with spaces on all my projects but that wasn't my intent.
Unfortunately I uninstalled this addon and now some files are with spaces and others are with tabs.

**Comment by rluiten** [comment]
All good, just noticed it.
