### ISSUE TITLE
Systray right-click menu blurry

### ISSUE THREAD

**Issue by KAMiKAZOW** [Adrianotiger/desktopPet#41]
The text of the systray menu is not HiDPI aware. The result is a blurry image.

![image](https://user-images.githubusercontent.com/3259076/71487045-0adc8280-2811-11ea-86d1-9e5395501ed9.png)

**Comment by Adrianotiger** [comment]
Thank you for the hint. Is there a way to reproduce it on every computer?
I found the documentation about it:

https://docs.microsoft.com/en-us/dotnet/framework/winforms/high-dpi-support-in-windows-forms

But I can't reproduce the blurry image on my computer to test if it works...

**Comment by Jnss98b** [comment]
I can reproduce it too. Maybe you can try viewing it through 1080p+ displays

![image](https://user-images.githubusercontent.com/24306400/71760089-6b8f4d80-2eea-11ea-9cfe-6b1cf502cecb.png)

**Comment by Adrianotiger** [comment]
Is it solved with the version 1.2.6?

**Comment by KAMiKAZOW** [comment]
Solved
