### ISSUE TITLE
Unreadable text in pet selection screen

### ISSUE THREAD

**Issue by KAMiKAZOW** [Adrianotiger/desktopPet#42]
How is anybody supposed to read this?

![image](https://user-images.githubusercontent.com/3259076/71487085-48411000-2811-11ea-9540-1decd679a740.png)

**Comment by Adrianotiger** [comment]
text is now black (from version 1.2.6).

**Comment by KAMiKAZOW** [comment]
No, it's not.
![image](https://user-images.githubusercontent.com/3259076/126227668-23fb44c4-0c01-4a35-aaf7-ab3b8afba11d.png)

![image](https://user-images.githubusercontent.com/3259076/126227723-046e2484-d042-4ac6-83b8-3ed50f14e61a.png)
