### ISSUE TITLE
Feature request for the flying saucer

### ISSUE THREAD

**Issue by montao** [Adrianotiger/desktopPet#45]
If I remember correctly, the original sheep could encounter a UFO which resulted in the sheep being abducted by the UFO (not 100 % sure that this is the case but it should be possible to verify). 

It would be great if this would work also in this C# version of the sheep. 

It is possible that there are also more features and scenarios that would be nice to include (both from the old original version and brand new scenarios).

**Comment by Adrianotiger** [comment]
Hi Montao.
Yes you're right. In my animation it is not present, but RedSparrow created an animation with much more movements and also the UFO. You can download it under options. Just download the green sheep:
![image](https://user-images.githubusercontent.com/7373079/73532422-f2b5df80-441c-11ea-960d-ab91bf281704.png)

**Comment by montao** [comment]
Awesome, it works!
