### ISSUE TITLE
peteditor: how to generate the .exe file?

### ISSUE THREAD

**Issue by ahahahaah** [Adrianotiger/desktopPet#51]
hello
i've just tested peteditor and added the animation for gravity.
when finished, i clicked the "save as" button that creates a .xml file.
but what to do if i want to have a .exe file to test it directly on my desktop? (i use windows)

**Comment by Adrianotiger** [comment]
There are some reserved words for the animation name:

https://github.com/Adrianotiger/desktopPet/wiki/XML%5CAnimation#name--

For example drag is used when you pick the pet. Kill is executed when the pet is removed from the desktop.

**Comment by ahahahaah** [comment]
i will check this,
thanks
