### ISSUE TITLE
mac os x

### ISSUE THREAD

**Issue by juney2008** [Adrianotiger/desktopPet#52]
can you guys add mac os x plz? i will love it if you do!

**Comment by Adrianotiger** [comment]
Hi Juney,
the entire project use a massive Windows-based libraries and functions. As windows detection is implemented in Windows. Probably you have it also on Linux-based OS, but the structure of the code should be a little bit different, I think.

I don't have any plan to bring it also on other OS, but the XML is universal and I was able to bring it to HTML5 with just a simple script. So probably it is also possible to have it on MacOs or other Linux distributions, but it is another world for me. I am happy to reopen this issue, if someone can port it to other OS.
