### ISSUE TITLE
Sytem Tray Menu closes in frequent intervalls.

### ISSUE THREAD

**Issue by rifoerster** [Adrianotiger/desktopPet#54]
When ever some interval is reached the system tray menu just closes on me, that can be very short (if i open the menu right before), or a bit later ( if i miss the interval by just a bit), but the whole thing makes adding more sheep or other tasks from the menu quiet annoying to trigger.

It only happens with esheep and no other system tray menus.

Version: 2.5 (Store Version) as of 28.10.2020
OS: Windows 10 - Version: 20H2

**Comment by Adrianotiger** [comment]
solved with the 2.6 version.
