### ISSUE TITLE
Green sheep ignores taskbar sometimes

### ISSUE THREAD

**Issue by LuisMayo** [Adrianotiger/desktopPet#55]
Green sheen may spawn inside the taskbar if it uses the meteor animation to spawn. Furthermore, black sheeps that may appear when using this pet spawn inside the taskbar too.

It wouldn't be a problem if it weren't for the fact that green sheep cannot get inside the taskbar by normal means, not even if I try to grab it and drop it in the taskbar

Is this the expected behavior?

**Comment by OliverPets** [comment]
I fixed this in the latest update (8.0) :)
