### ISSUE TITLE
Online pets not available

### ISSUE THREAD

**Issue by speedyhoon** [Adrianotiger/desktopPet#61]
I've just installed and found the Online Pets tab is not working. Is this expected?
I'm using Windows 8.0 and don't have a proxy configured for my internet connection or anything.
![image](https://user-images.githubusercontent.com/16303791/108579584-c482a500-737b-11eb-9622-391238d1752d.png)

**Comment by Adrianotiger** [comment]
Hi,
You have a very old version of the application. 

Please update it with a new version. On github, you can find the last release.

**Comment by speedyhoon** [comment]
I'm experiencing the same issue with version 1.2.5.

**Comment by Adrianotiger** [comment]
The page to load is this:
https://adrianotiger.github.io/desktopPet/Pets/download.html

Can't understand why it should not be able to load. Maybe a ssl problem. Or the app doesn't have the right to access the web?

**Comment by Adrianotiger** [comment]
It was solved.
And with the latest release (1.3.1), the IE-component was replaced.
