### ISSUE TITLE
Download issue

### ISSUE THREAD

**Issue by Khajababa** [Adrianotiger/desktopPet#66]
I feel like a complete idiot for asking a simple question like this, I'm sure that it's right in front of my eyes but I can't see it. 
I haven't been able to figure how to download the latest version 1.2.5 (https://github.com/Adrianotiger/desktopPet/releases/tag/v1.2.5) 
I can't run DesktopPet.gz file, isn't there an exe? I am currently using the old 1.2.1 version (https://github.com/Adrianotiger/desktopPet/releases/tag/desktop1.2.1) that has an .exe on the download page.
How can I download the latest version?
By the way, I am a big fan of the project! thank you for bringing back esheep!

**Comment by Adrianotiger** [comment]
Gz is a zipped file. You need a zip program like winzip, winrar or 7zip to open it. Inside the zip you find the exe.

I can't upload the exe anymore as it isn't signed.

**Comment by Khajababa** [comment]
Thank you!

**Comment by Adrianotiger** [comment]
You're welcome 😊
