### ISSUE TITLE
Bowser Jr. Pet not available 

### ISSUE THREAD

**Issue by deonsebastiandk** [Adrianotiger/desktopPet#75]
i was trying to bring another pet called bowser jr. to my desktop . but when i saw online pets there was no bowser jr. available . but when i checked the old website - https://esheep.petrucci.ch but the website was saying that it was still available . please republish bowser jr.

**Comment by Adrianotiger** [comment]
Yes, on the old version there was a lot of pets. The most was just to try or test the app.
Bowser had just 4-5 animations, so it was not a nice desktop mate.

But I can try to port it to github. Or, if you want, you can try to use the pet editor 😊 and upload your project!

**Comment by deonsebastiandk** [comment]
Ok

**Comment by deonsebastiandk** [comment]
Please port it to github !
