### ISSUE TITLE
[Suggestion] Please port DesktopPet into android and linux

### ISSUE THREAD

**Issue by RandomPenguin1778** [Adrianotiger/desktopPet#82]
Hello ! I realized that the DesktopPet is available for windows users but not for android and linux . please port the DesktopPet into linux and the reason why i am asking for android is because The 'DesktopPet' port in the google playstore isn't same like this . it doesn't have features and many other things which the DesktopPet has . So please try to port DesktopPet into linux and android .

**Comment by Adrianotiger** [comment]
The code is written in.net and uses many windows dll to detect windows on the screen.

Maybe with.net 6 this will be possible. Currently this is not possible. I have to rewrite the entire application.

Web sheep is another project, that is able to use the same animations like the Windows application. Maybe someone can write it for Linux. I could try to develop it for android, just without windows detection. But should be possible with xamarin.

**Comment by deonsebastiandk** [comment]
But could you rewrite it or should we wait till .net 6 is released ?

**Comment by Adrianotiger** [comment]
MS released a beta. But I was able to write a simple app for Android, leaving the esheep on top.
Probably I can use the entire c# code used for the Windows application.
![Screenshot_20210510-172328.png](https://user-images.githubusercontent.com/7373079/117683941-d4f52f80-b1b4-11eb-96d1-81ef2d1df524.png)

**Comment by deonsebastiandk** [comment]
Does it have features like desktop pet ?

**Comment by deonsebastiandk** [comment]
But can you make a port for Linux?

**Comment by Adrianotiger** [comment]
If you want to try it ;)

[ch.petrucci.androsheep.apk.zip](https://github.com/Adrianotiger/desktopPet/files/6466477/ch.petrucci.androsheep.apk.zip)

It just opens the xml and try to animate it over your screen. To close the app, just click on the sheep.
Important: You need to allow the app to run as service.

There are many things I don't understand, like how to get the size of the screen, keybar, pet and what I need to convert to pixels or dp.

And there is no window detection... as there aren't windows in Android :P

**Comment by OliverPets** [comment]
Doesn't let me install on my phone unfortunately but I'm sure porting to android would be very hard so I'm not upset lol

**Comment by Adrianotiger** [comment]
It was unsigned...
But I uploaded it also on the store.

You should be able to download it here:
https://play.google.com/store/apps/details?id=ch.petrucci.androsheep

**Comment by OliverPets** [comment]
Wow it works!!! That's so cool!! Any way to change the XML file? :D

**Comment by Adrianotiger** [comment]
Yes, will be the next step. It was a 2 hours project. Just to see if it would be possible.
The real works begins when I have to implement all pets 😜
But I will work on it.

Can I use your sheep as default pet?

**Comment by OliverPets** [comment]
Absolutely yeah!!

**Comment by deonsebastiandk** [comment]
But can anyone rewrite the desktop pet application for linux using visual studio ?

**Comment by Adrianotiger** [comment]
@deonsebastiandk I am not a team. I am just a single programmer. And since I just have base Linux knowledges, I am not able to port this project to Linux. But I can leave open this issue until someone on the world will try to port it to Linux. As said, what you need is to detect windows on your desktop and I am not sure that you will be able to do it on Linux (or at least not without root permissions). There isn't any `user32.dll` on Linux.

@OliverPets Thanks :D I will replace my boring sheep with yours! At the moment there is just a little problem. On Windows you can evaluate the expression: "100 + Convert(5434.3, Int32)". This does not work on the web-eSheep or java-eSheep.
A better way would be to use "100 + (int)(5434.3)", but this does not work in Windows.
And also, unfortunately, Java is not able at all to evaluate any expressions. So I have to import a Javascript engine or an external library to Java to evaluate the expression :P This is just what I detected when I was trying to port the animations to Android. 
I saw that you are using even more complicated expressions using windows expressions. They doesn't work on javascript or java - we need to find an universal solution or at least a way to convert it to the other systems.

**Comment by deonsebastiandk** [comment]
OK .

**Comment by deonsebastiandk** [comment]
I meant the wine emulator for linux .

**Comment by Adrianotiger** [comment]
@deonsebastiandk Yes, it still should work. Last year there was a graphic problem. I don't have a Linux distribution to try at the moment. 

@OliverPets just uploaded a new version to the play store. Now you should be able to play your pets too. I solved a lot of my problems measuring correctly all android bars (status, top bar and bottom button bar). What you can't do is play childs or create more than 1 pet on a single instance... I need to write the entire code twice to let another pet walking on the screen and this is not a good solution :P 
But version 2.0 should be available in the store in the next hours.

**Comment by deonsebastiandk** [comment]
@Adrianotiger So can you try it in VM ?

**Comment by deonsebastiandk** [comment]
@Adrianotiger Can i be the tester for this android port ? i can post any issues or bugs coming with this application .

**Comment by deonsebastiandk** [comment]
@Adrianotiger I will try the desktop pet in my Linux VM

**Comment by OliverPets** [comment]
@Adrianotiger It works incredibly well! The pet does all the same stuff like normal on my phone. No child spawns is okay, but some stuff will look weird :P There's two improvements that I would love to see: The pet staying open when you turn off your phone screen. When I unlock my phone, the pet is gone. And the pet rotating with the screen in landscape mode. Those two things would make it feel way better to keep on my phone!!

**Comment by deonsebastiandk** [comment]
@Adrianotiger The Port is very good . now i can download pets from github . can i be the bug reporter of this port ?

**Comment by Adrianotiger** [comment]
> @Adrianotiger The Port is very good . now i can download pets from github . can i be the bug reporter of this port ? 

Thanks, but I already know that it is not complete and that there are many bugs. I am just try to see what I can do on android 😉
It is an alpha version. Not beta.
If someone can help me, I will upload the code. If not, probably it will never be released as stable app 😜 too much work!

**Comment by deonsebastiandk** [comment]
@Adrianotiger Can i put the android port link in the download.md file ? i will say that this might be unstable in the description , so can i edit the download.md file ?

**Comment by RandomPenguin1778** [comment]
Hi Adriano , I wanted to add my own pet called 'Haiku' . so i forked the desktop pet repository and made some changes to it . so can you bring my fork repository changes to the desktop pet repository . here is the forked repository link - https://github.com/RandomPenguin1778/desktopPet/tree/master/Pets/

**Comment by RandomPenguin1778** [comment]
Hi Adriano , Can you merge my pull requests ?

**Comment by Adrianotiger** [comment]
Please make a single merge request from the entire project. Not a request for each single file. It will not work if you just ask to merge 2 single files.

**Comment by RandomPenguin1778** [comment]
Hi Adriano , can you add me in the repository . that way i could upload my pets . but if you want to merge my fork with your project here is the fork link - https://github.com/deonspets6783/desktopPet/ . i forked this project on my other github account .

**Comment by Adrianotiger** [comment]
> Hi Adriano , can you add me in the repository . that way i could upload my pets . but if you want to merge my fork with your project here is the fork link - https://github.com/deonspets6783/desktopPet/ . i forked this project on my other github account . 

I can't make a request from your project. But you can read how to do it in the link I sent you some weeks ago. It is written in the tutorial.

**Comment by Adrianotiger** [comment]
I close this topic as there are too much off topic comments.

**Comment by RandomPenguin1778** [comment]
I am sorry, I won't put off topic issues again in this discussion.  Please reopen this issue for somebody to see this discussion and port it to linux
