### ISSUE TITLE
Error when dragging beta pet

### ISSUE THREAD

**Issue by RedSparr0w** [Adrianotiger/desktopPet#9]
### Beta pet `417` - SSJ Goku

Error Message appears roughly 1-3 seconds after drag start (image below).
Once the message appears the pet stays in place and is no longer movable,
you can still add more pets afterwards though while that one remains.

![error message](https://i.imgur.com/OyJmD06.png)
More Info:
![](https://i.imgur.com/6QQcZKN.png)

It looks to me like its adding an extra comma to the end of the drag sequence. not sure why though.

If you need any more information let me know.

**Comment by RedSparr0w** [comment]
Looks like its happening on `kill` aswell.
![](https://i.imgur.com/LhJPtn8.png)
More Info:
![](https://i.imgur.com/cvyI2by.png)

I have double & triple checked the generator settings:
![](https://i.imgur.com/zEjQkIu.png)
![](https://i.imgur.com/ldxxmKS.png)

**Comment by RedSparr0w** [comment]
If i change the `repeats counts` & `repeats from` to 0 the error stops appearing.
![](https://i.imgur.com/4rhlcm0.png)

**Comment by Adrianotiger** [comment]
Hi RedSparrow,
thank you for trying using the online editor and for making an animation :)
It has to do with the **repeats from** value. It is an index (beginning from 0) and not with the values count.
So if you have 3 values on the sequence, you can insert only a value from 0 to 2. The online editor still doesn't check that kind of errors (or even if you set next to an invalid sequence id). It is something that I have to solve :)

**Comment by RedSparr0w** [comment]
Thanks for that, 
You have done an awesome job on this project, I definitely would not have been able to make the goku without the editor, Took me a little while to figure it all out (and get the sprites spaced evenly) but i got there in the end [=.

I tried setting the following options:
```
repeats count: 10
repeats from: 1
sequence: 5,4
```
but it just seemed to get stuck on the last animation (windows 10 64bit) or crash with the error (windows server 2008 r2)

Its strange because the other animations have worked fine for me like this, oh well solved now.
---------------------------------
Also where should feature request be posted? (here or the main website?)
